### ISSUE TITLE
Setup succeeded, but issued commands fail 

### ISSUE THREAD

**Issue by mattenz** [iainbullock/tesla-http-proxy-docker#35] opened 2024-04-07 03:12 UTC
So I've managed to get through all the config steps and as far as I can tell, everything succeeded - I even see the "key" in the car. However, when I try to test the proxy with any command, I get back something like this (I've redacted my actual VIN):

```
2024-04-07T02:37:02Z [info ] Received POST request for /api/1/vehicles/VIN/command/door_unlock
2024-04-07T02:37:02Z [debug] Executing door_unlock on VIN
2024-04-07T02:37:02Z [info ] Starting dispatcher service...
2024-04-07T02:37:02Z [info ] Requesting session info from DOMAIN_INFOTAINMENT
2024-04-07T02:37:02Z [info ] Requesting session info from DOMAIN_VEHICLE_SECURITY
2024-04-07T02:37:02Z [debug] Sending request to https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/vehicles/VIN/signed_command: {"routable_message":"MgIIAzoSEhBAIVQMexRBgt5zfZ0KYc13mgMQ+B+csVnZAkedljj3uL/OAnJDCkEEmEBzB7wfYjaCrI110KzVl/JFiDAy5rgWwdXkgS+eFkCkTA5pFoAI5wsiKFjXfEzVT8AyzT1Td5OWazDf8bLrSA=="}
2024-04-07T02:37:02Z [debug] Sending request to https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/vehicles/VIN/signed_command: {"routable_message":"MgIIAjoSEhDCvmbFnL6PDJ2PccKcxsoCmgMQFzmNNofJqiZuWgSayrtDN3JDCkEEmEBzB7wfYjaCrI110KzVl/JFiDAy5rgWwdXkgS+eFkCkTA5pFoAI5wsiKFjXfEzVT8AyzT1Td5OWazDf8bLrSA=="}
2024-04-07T02:37:02Z [debug] Server returned 404: Not Found: {"response":null,"error":"not_found","error_description":"","txid":"9d0ecfd91d4f5c4df3a0446d2fad5cb9"}
2024-04-07T02:37:02Z [warn ] [f81f9cb159d902479d9638f7b8bfce02] Terminal transmission error: {"response":null,"error":"not_found","error_description":"","txid":"9d0ecfd91d4f5c4df3a0446d2fad5cb9"}
2024-04-07T02:37:02Z [error] Returning error Not Found
2024-04-07T02:37:02Z [debug] [17398d3687c9aa266e5a049acabb4337] Retrying transmission after error: Post "https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/vehicles/VIN/signed_command": context canceled 
```

If I run curl `--cacert selfsigned.pem --header "Authorization: Bearer $TESLA_AUTH_TOKEN" "https://proxy:4430/api/1/vehicles/"` I get back:
`{"response":[],"pagination":{"previous":null,"next":null,"current":1,"per_page":100,"count":0,"pages":1},"count":0}`

My API scopes look like this:
![image](https://github.com/iainbullock/tesla-http-proxy-docker/assets/7954780/33ac9313-c6e8-4504-ba00-77672f307b5b)

Any idea what I've done wrong?

**Comment by iainbullock** [comment] 2024-04-07 13:40
I'm away at the moment so not got a lot of time to look into this. My scope has 'Profile Information' included. Not sure if that's an issue or not?

**Comment by jesserockz** [comment] 2024-04-07 22:10
I have the same scopes as above and it works, so `Profile Information` is not required.

**Comment by mattenz** [comment] 2024-04-08 05:12
As a test, I did try updating the scopes to include all of them since making this issue but that made no difference on the result, unfortunately.

**Comment by iainbullock** [comment] 2024-04-08 08:22
Not sure what's wrong here. Tesla API documentation ( https://developer.tesla.com/docs/fleet-api#response-codes ) on response codes isn't helpul: '404 | Not Found | The requested resource does not exist.'

Here's my output after sending a similar command, not sure if it helps:

2024-04-08T08:03:02Z [info ] Received GET request for /api/1/vehicles/LRW3XXXXXXXXXXX03
2024-04-08T08:03:02Z [debug] Forwarding request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/vehicles/LRW3XXXXXXXXXXX03
2024-04-08T08:03:02Z [info ] Received POST request for /api/1/vehicles/LRW3XXXXXXXXXXX03/command/charge_port_door_open
2024-04-08T08:03:02Z [debug] Executing charge_port_door_open on LRW3XXXXXXXXXXX03
2024-04-08T08:03:02Z [info ] Starting dispatcher service...
2024-04-08T08:03:02Z [info ] Session for DOMAIN_INFOTAINMENT loaded from cache
2024-04-08T08:03:02Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2024-04-08T08:03:02Z [debug] Sending request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/vehicles/LRW3XXXXXXXXXXX03/signed_command: {"routable_message":"MgIIAzoSEhBq+9L1eFtqDriZnWuiRs4qmgMQ9bJ1x/LPdixymozoCVNi4VIFEgPyAwBqggEKQwpBBLzmP7shmOn11rKWYq79TZJ+FgF17fAsEh2vPfDNymsoFsg/GhZ4SEHHlef0iuRxqLV73VxAqQkCsDfJzlzOXllCOwoQ7Cs28s3M07cD4sB/0B3ijxABHavdAAAiIHBR6V+eEoF0CA3hYqWadQR190W2oLz/9TdR6P4fRwmk"}
2024-04-08T08:03:02Z [debug] Server returned 200: OK: {"response":"MhISEGr70vV4W2oOuJmda6JGzio6AggDYgCSAxD1snXH8s92LHKajOgJU2LhmgMQE2CJhXb6cMufP8OeqAVAwVICCgA="}

Could your VIN be incorrect? I appreciate it is obtained automatically so it shouldn't be. Do you have more than one vehicle and it's somehow trying to access the wrong one?

I'll do the same using curl shortly and post the result

**Comment by mattenz** [comment] 2024-04-08 08:57
I thought maybe I had the VIN incorrect too, but I double and triple checked but it still returns the same results. It also wouldn't explain why just querying the vehicles endpoint returns nothing as well. I am in New Zealand and from what I can tell, "North America, Asia-Pacific" is the correct region to go with in my config.sh file?

I only have the one vehicle but it just seems like it isn't seeing that the vehicle exists...

**Comment by iainbullock** [comment] 2024-04-08 08:58
OK here's my tests using curl. I created a new access_token using iOS Auth for Tesla, and put it in /data/access_token. I then executed the following commands from the shell on my docker host:

```
export TESLA_AUTH_TOKEN=`cat access_token`
export VIN=LRW3XXXXXXXXXXX03

```
Firstly, test the API:
curl --cacert cert.pem  --header "Authorization: Bearer $TESLA_AUTH_TOKEN"  "https://macmini.home:4430/api/1/vehicles"
Which returned the following (note the VIN is returned - check it's correct for your case):
{"response":[{"id":929899918489429,"vehicle_id":1689319467215956,"vin":"LRW3XXXXXXXXXXX03","color":null,"access_type":"OWNER","display_name":"The Pearl","option_codes":null,"granular_access":{"hide_private":false},"tokens":["a34XXXXXXXXXXXX3","5ecXXXXXXXXXXXXa"],"state":"asleep","in_service":false,"id_s":"92XXXXXXXXXXXX9","calendar_enabled":true,"api_version":73,"backseat_token":null,"backseat_token_updated_at":null,"ble_autopair_enrolled":false}],"pagination":{"previous":null,"next":null,"current":1,"per_page":1,"count":1,"pages":1},"count":1}

Now I'll send a command:
curl --cacert cert.pem --header 'Content-Type: application/json'  --header "Authorization: Bearer $TESLA_AUTH_TOKEN"  --data '{"which_trunk": "rear"}'  "https://macmini.home:4430/api/1/vehicles/$VIN/command/actuate_trunk"

Which works as expected and returns the following:
{"response":{"result":true,"reason":""}}

Corresponding logs from the proxy are:
2024-04-08T08:44:00Z [info ] Received POST request for /api/1/vehicles/LRW3XXXXXXXXXXX03/command/actuate_trunk
2024-04-08T08:44:00Z [debug] Executing actuate_trunk on LRW3XXXXXXXXXXX03
2024-04-08T08:44:00Z [info ] Starting dispatcher service...
2024-04-08T08:44:00Z [info ] Session for DOMAIN_INFOTAINMENT loaded from cache
2024-04-08T08:44:00Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2024-04-08T08:44:00Z [debug] Sending request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/vehicles/LRW3XXXXXXXXXXX03/signed_command: {"routable_message":"MgIIAjoSEhAwwegNl6raRHJ+PF6dpjfgmgMQGwixMsfGQ3m+949xDq6uElIEIgIoAWqCAQpDCkEEvOY/uyGY6fXWspZirv1Nkn4WAXXt8CwSHa898M3KaygWyD8aFnhIQceV5/SK5HGotXvdXECpCQKwN8nOXM5eWUI7ChAvJ/2EEm8MDUWiaKFbXsY8EA8dVKYCACIg1LSkbgCbpD3FAGRteUDXU14DBZReFKFIM/uH+LKwVKA="}
2024-04-08T08:44:01Z [debug] Server returned 200: OK: {"response":"MhISEDDB6A2XqtpEcn48Xp2mN+A6AggCeloSQQQe7tG/mnsuBWVVq3TBqux0sT+of+2Cm/owU6Bw5OHTRjV3gRdfeQ/BWwZb7RiCVazbMSxEVZ0y3uWJyMTnhKIFGhAOtUmSmF5Bsfrouj68OWpfJaMQAABiBAgCEA9qJDIiCiB7UGEqMUpVTaFmfiKKrXkhLSRFNWwWq0ZoIjedBnySRpIDEBsIsTLHxkN5vvePcQ6urhI="}
2024-04-08T08:44:01Z [info ] [1b08b132c7c64379bef78f710eaeae12] Updated session info for DOMAIN_VEHICLE_SECURITY
2024-04-08T08:44:02Z [debug] Sending request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/vehicles/LRW3XXXXXXXXXXX03/signed_command: {"routable_message":"MgIIAjoSEhAHu6XlkTx+gmDH2rc7aE9jmgMQPuBXF4k7BS8YWEngneEdRFIEIgIoAWqCAQpDCkEEvOY/uyGY6fXWspZirv1Nkn4WAXXt8CwSHa898M3KaygWyD8aFnhIQceV5/SK5HGotXvdXECpCQKwN8nOXM5eWUI7ChAOtUmSmF5Bsfrouj68OWpfEBAdrBAAACIgHh2KIuxEOsfS9LYCwonPeX9FXUc7kLHiTeC/RNKcxM0="}

Not sure if this helps?

**Comment by iainbullock** [comment] 2024-04-08 09:02
> I thought maybe I had the VIN incorrect too, but I double and triple checked but it still returns the same results. It also wouldn't explain why just querying the vehicles endpoint returns nothing as well. I am in New Zealand and from what I can tell, "North America, Asia-Pacific" is the correct region to go with in my config.sh file?
> 
> I only have the one vehicle but it just seems like it isn't seeing that the vehicle exists...

Sorry I posted again just as you replied. Some of the other people on who are active on https://github.com/iainbullock/tesla-http-proxy-docker/issues/19 are in AU or NZ and I believe are successfully using "North America, Asia-Pacific" region @dasviridov @jesserockz could you confirm?

**Comment by mattenz** [comment] 2024-04-08 09:17
Is my 2019 Model 3 too old for the API? Or just potentially not been transferred over? The old API still works for it, but given all the warnings from Tesla that it’s being shutdown I figured I should start getting this working.

**Comment by iainbullock** [comment] 2024-04-08 09:21
I don't know but that could well be the explanation. If so, I think you have gone as far as you can do with this until your car is recognised by the newer Fleet API. Have a look at the 'parent' project to see if anyone is reporting a similar issue. It's much busier than my project, but as I essentially copied most of the code from there, it works the same way, so should have the same issue.

https://github.com/llamafilm/tesla-http-proxy-addon

**Comment by dasviridov** [comment] 2024-04-08 11:20
@iainbullock, for AU and NZ - North America, Asia-Pacific is the right region. If region is wrong the error message is different.

@mattenz, as far as I know Tesla is moving cars to the new API by stages. So not all cars are being moved at the same time. Mine is 2022 model Y. It did work on old API up until mid March 2024. I think they do move them in backward order, so the newer the model the faster it got switched.

If it works for you I suggest you keep using Owner API up until it starts giving auth errors.

Otherwise if you eager to move and you have some developer experience, it should be possible to call their API directly by using something like Postman or curl. It's just a regular REST API and and is well documented from what I can see. If direct calls give you some info, then the issue is on the proxy / integration side. Оtherwise the car is not yet transferred to the new API.

**Closed** 2024-04-08 11:34 UTC
